name: Hype Streaming Extension Services

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install --save-dev
      - run: ./node_modules/.bin/tslint --project tsconfig.json
      - run: npm run test
      - run: ./node_modules/.bin/tsc

