name: Hype Streaming Extension Services

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install --save-dev

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: ./node_modules/.bin/tslint --project tsconfig.json

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: tsc

